
# Offense count: 16
# Configuration parameters: AllowedConstants.
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'cargo_carriage.rb'
    - 'cargo_train.rb'
    - 'carriage.rb'
    - 'instance_counter.rb'
    - 'manufacturerable.rb'
    - 'menu/main_menu.rb'
    - 'menu/route_menu.rb'
    - 'menu/station_menu.rb'
    - 'menu/text_menu.rb'
    - 'menu/train_menu.rb'
    - 'passanger_carriage.rb'
    - 'passanger_train.rb'
    - 'utils.rb'
    - 'utils/string_utils.rb'
    - 'validatable.rb'

